### ISSUE TITLE
Dynamic changes category does not include WCAG 4.1.3 Status Messages

### ISSUE THREAD

**Issue by MarcSolo** [canaxess/thisiswcag#1]
This is a super valuable resource, thanks for sharing it with the community! Please consider adding WCAG 4.1.3 Status Messages under the dynamic content category. I think of status messages as dynamic content and suspect others might as well.

**Comment by rossmullen** [comment]
Thanks for the suggestion @MarcSolo I've added dynamic content to the category for 4.1.3 Status Messages.
