### ISSUE TITLE
Success criterion 1.4.12 seems odd

### ISSUE THREAD

**Issue by vasilisvg** [canaxess/thisiswcag#3]
https://github.com/canaxess/thisiswcag/blob/585a3fd997911c69586adf11099bff6a7de1622e/data/json.js#L49

It now reads:

> there is no loss of content or functionality when the https://dylanb.github.io/bookmarklets.html is applied

This looks like a copy and paste mistake?

**Comment by rossmullen** [comment]
This isn't a copy/paste mistake, the test is for applying the bookmarklet found at the address https://dylanb.github.io/bookmarklets.html. The bookmarklet link at the address is dragged to the address bar and applied to web content, if the content or functionality can still be used once applied it passes this success criteria.
