### ISSUE TITLE
I find criterion 2.4.5 a bit confusing

### ISSUE THREAD

**Issue by vasilisvg** [canaxess/thisiswcag#4]
https://github.com/canaxess/thisiswcag/blob/585a3fd997911c69586adf11099bff6a7de1622e/data/json.js#L71

Criterion 2.4.5 now reads:

> at least 2 of related pages, table of contents, site map, site search, or list of web pages must be provided for non-workflows

There are a few things that make this sentence confusing to me. The start of the sentence seems odd. I don’t think I understand what "At least 2 of related pages" means.
I think the end of the sentence is confusing as well. What are *non-workflows?*

**Comment by rossmullen** [comment]
This may benefit from rewording. It means if at least 2 items from the following list exist, the success criteria is passed.
- related pages
- table of contents
- site map
- site search

Workflows are part of a multi stage process such as changing items details, or completing a purchase those pages are exempt from this success criteria as those pages contribute to the entire workflow of _completing x_.
