### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pkowalli** [canaxess/thisiswcag#5]
I think this text has a typo - and this sentence is hard to understand (as a non-native speaker):
a te**x**t or exercise invalid if presented in text has text identification describing the non-text content

Should be
a te**s**t or exercise invalid if presented in text has text identification describing the non-text content.

**Comment by rossmullen** [comment]
Thanks @pkowalli I agree, this is confusing to read. I've updated it to read `an invalid test or exercise presented by an image has text identification describing the non-text content`
