### ISSUE TITLE
Consider adding category "colour" to SC 1.4.3 (Contrast (Minimum))

### ISSUE THREAD

**Issue by polarbirke** [canaxess/thisiswcag#6]
I found it odd that `1.4.3 Contrast`, a colour-related AA success criterion, was not listed in the "colour" category.

This project is a nice resource to point to for people starting into a11y, thank you for the good work! 👍

**Comment by rossmullen** [comment]
Thanks @polarbirke, great suggestion. the colour category suggestion has been added.
